### ISSUE TITLE
Docke-compose implementation

### ISSUE THREAD

**Issue by catalinvr** [egaillardon/jmeter-plugins#1]
Hello @egaillardon 

I started to run my tests with the latest docker image that you published.
Later I decided that I wanted to have a distinct directory for logs and one for results, so I decided to put everything in docker-compose.

The main problem is that your entry point is not working well and it was needed to use jmeter as entrypoint.

In case you consider this topic relevant, please can you add a demo with docker-compose.

Thank you,
Catalin

**Comment by egaillardon** [comment]
Hello @catalinvr 
Sorry for my late reply :(
Could you please, provide me your docker-compose file ?
Thank you.
Emmanuel

**Comment by catalinvr** [comment]
Hi @egaillardon, 

Here it is:
```
version: '3.7'

services:
  jmeter:
    container_name: jmeter
    image: docker.io/egaillardon/jmeter-plugins:5.2.1-1.2.0
    privileged: true
    entrypoint: jmeter
    volumes:
      - ./sources:/sources
      - ./logs:/logs
      - ./results:/results
    command:
      - '--nongui'
      - '-t/sources/${test_file}'
      - '-l/results/result.jtl'
      - '-j/logs/jmeter.log'
      - '-e'
      - '-o/results/dashboard/'
      - '-LDEBUG'
```

**Comment by egaillardon** [comment]
Hello @catalinvr
I tried with the following dockerfile:
```
version: '3.7'
services:
  jmeter:
    container_name: jmeter
    image: docker.io/egaillardon/jmeter-plugins:5.2.1-1.2.0
    privileged: true
#    entrypoint: jmeter
    volumes:
      - ./sources:/sources
      - ./logs:/logs
      - ./results:/results
    command:
      - '--nongui'
      - '-t/sources/file.jmx'
      - '-l/results/result.jtl'
      - '-j/logs/jmeter.log'
      - '-e'
      - '-o/results/'
      - '-L DEBUG'
```
and the entrypoint worked fine: 
```
$ docker-compose up
Creating jmeter ... done
Attaching to jmeter
jmeter    | Apr 27, 2020 7:46:43 PM java.util.prefs.FileSystemPreferences$1 run
jmeter    | INFO: Created user preferences directory.
jmeter    | Creating summariser <summary>
jmeter    | Created the tree successfully using /sources/file.jmx
jmeter    | Starting standalone test @ Mon Apr 27 19:46:43 GMT 2020 (1588016803459)
jmeter    | Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
jmeter    | summary +      4 in 00:00:20 =    0.2/s Avg:     0 Min:     0 Max:     1 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
jmeter    | summary +      6 in 00:00:30 =    0.2/s Avg:     0 Min:     0 Max:     0 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
jmeter    | summary =     10 in 00:00:50 =    0.2/s Avg:     0 Min:     0 Max:     1 Err:     0 (0.00%)
jmeter    | Command: StopTestNow received from /127.0.0.1
jmeter    | summary +      3 in 00:00:19 =    0.2/s Avg:     0 Min:     0 Max:     0 Err:     0 (0.00%) Active: 0 Started: 1 Finished: 1
jmeter    | summary =     13 in 00:01:10 =    0.2/s Avg:     0 Min:     0 Max:     1 Err:     0 (0.00%)
jmeter    | Tidying up ...    @ Mon Apr 27 19:47:54 GMT 2020 (1588016874062)
jmeter    | ... end of run
jmeter exited with code 0
```
```
$ docker inspect --format='{{.Path}}' jmeter
/usr/local/bin/entrypoint.sh
```

Could you, please, be more specific ? Do you have any message that can help ?
